name: Compile Typst files

on:
  push:
    paths:
      - '**/*.typ'
  pull_request:
    paths:
      - '**/*.typ'

jobs:
  compile-typst-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Typst
        run: |
          curl -fsSL https://github.com/typst/typst/releases/download/v0.5.0/typst-0.5.0-linux-x86_64.tar.gz | tar -xz -C /usr/local/bin
          typst update

      - name: Find and compile Typst files
        run: |
          # Find all .typ files and compile them to .pdf in ./pdf/ folder
          find . -type f -name "*.typ" | while read -r file; do
            output="./pdf/$(basename "${file%.*}.pdf")"
            mkdir -p "$(dirname "$output")"
            typst compile "$file" "$output"
          done
      - name: GIT commit and push overriding conflicts with local changes (verbose)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pdf/*.pdf
          git commit -m "Compiled to pdf"
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          git push