
name: Compile to pdf

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Set up Typst
        run: |
          sudo snap install typst

      - name: Install font
        run: |
          cd $(mktemp -d /tmp/script.XXXXXXX)
          TEMP_DIR=$(pwd)
  
          mkdir -p ~/.fonts
  
          wget https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip
          unzip 1.050R-it.zip
          cp source-code-pro-2.030R-ro-1.050R-it/OTF/*.otf ~/.fonts/
  
          wget https://github.com/adobe-fonts/source-serif-pro/archive/2.000R.zip
          unzip 2.000R.zip
          cp source-serif-pro-2.000R/OTF/*.otf ~/.fonts/
  
          wget https://github.com/adobe-fonts/source-sans-pro/archive/2.020R-ro/1.075R-it.zip
          unzip 1.075R-it.zip
          cp source-sans-pro-2.020R-ro-1.075R-it/OTF/*.otf ~/.fonts/
  
          fc-cache -f -v
    
      - name: Find and compile Typst files
        run: |
          # Find all .typ files and compile them to .pdf in ./pdf/ folder
          find . -type f -name "*.typ" | while read -r file; do
            output="./pdf/$(basename "${file%.*}.pdf")"
            mkdir -p "$(dirname "$output")"
            typst compile "$file" "$output"
          done
          
      - name: GIT commit and push overriding conflicts with local changes (verbose)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pdf/*.pdf
          git commit -m "Compiled to pdf"
          git fetch origin
          git rebase --strategy-option=theirs origin/main
          git push
